/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STM32F103x6.h"
#include "STM32F103x6_GPIO_Driver.h"
#include "STM32F103x6_EXTI_Driver.h"
#include "STM32F103x6_RCC_Driver.h"
#include "STM32F103x6_USART_Driver.h"
#include "STM32F103x6_SPI_Driver.h"
#include "STM32F103x6_I2C_Driver.h"
#include "STM32F103x6_GPTIM_Driver.h"


#include "EEPROM_SlaveI2C.h"
#include "LCD2x16.h"
#include "Keypad.h"
#include "EEPROM_SlaveSPI.h"
#include "LED.h"
#include "ServoMotor_PWM.h"
#include "IRSensor.h"
#include "Buzzer.h"

#include "Admin.h"
#include "Gate.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

char arrRFID_usart1buffer[7] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
static uint8_t arrRFID_usart1buffer_INDEX = 0;
uint8_t Ch1;
void myUSART1Handler()
{

	MCAL_USART_ReceiveData(USART1, (uint16_t*) &Ch1, USART_Interrupt);
	MCAL_USART_SendData(USART1, (uint16_t*) &Ch1, USART_Polling);

	arrRFID_usart1buffer[arrRFID_usart1buffer_INDEX] = Ch1;
	arrRFID_usart1buffer_INDEX++;

	if (arrRFID_usart1buffer_INDEX == 4)
	{
		arrRFID_usart1buffer[arrRFID_usart1buffer_INDEX] = 0x00;

		if (APP_Search_RFID(arrRFID_usart1buffer) != 0) 		// RFID Matched
		{
			// Action when authorized RFID tag.
			HAL_LED_ON(LedGreenEntrance_Port, LedGreenEntrance_PinNumber);
			APP_EntranceGate();
			HAL_LED_OFF(LedGreenEntrance_Port, LedGreenEntrance_PinNumber);
		}
		else
		{
			// Action when authorized RFID tag
			HAL_LED_ON(LedRedEntrance_Port, LedRedEntrance_PinNumber);
		}

		arrRFID_usart1buffer_INDEX = 0;
	}
}


char arrRFID_usart2buffer[7] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF};
static uint8_t arrRFID_usart2buffer_INDEX = 0;
uint8_t Ch2;
void myUSART2Handler()
{

	MCAL_USART_ReceiveData(USART2, (uint16_t*) &Ch2, USART_Interrupt);
	MCAL_USART_SendData(USART2, (uint16_t*) &Ch2, USART_Polling);

	arrRFID_usart2buffer[arrRFID_usart2buffer_INDEX] = Ch2;
	arrRFID_usart2buffer_INDEX++;

	if (arrRFID_usart2buffer_INDEX == 4)
	{

		arrRFID_usart2buffer[arrRFID_usart2buffer_INDEX] = 0x00;

		if (APP_Search_RFID(arrRFID_usart2buffer) != 0) 		// RFID Matched
		{
			// Action when authorized RFID tag.
			//HAL_LED_ON(LedGreenExit_Port, LedGreenExit_PinNumber);
			APP_ExitGate();
			//HAL_LED_OFF(LedGreenExit_Port, LedGreenExit_PinNumber);
		}
		else
		{
			// Action when authorized RFID tag
			//HAL_LED_ON(LedRedExit_Port, LedRedExit_PinNumber);
		}

		arrRFID_usart2buffer_INDEX = 0;
	}
}

void clock_init()
{
	RCC_GPIOA_CLK_EN(); //Enable PORTA Clock
	RCC_GPIOB_CLK_EN(); //Enable PORTB Clock
	RCC_AFIO_CLK_EN();	//Enable AFIO Clock
}
void TIM2_init()
{
	MCAL_TIM_Init(TIM2, 0xFFFF, 1);
}
void LCD_init()
{
	HAL_LCD_Init(FunctionSet_4Bit_2Line_5x8Dots, DisplayControl_DisplayOn_CursorOn_BlinkOff, EntryModeSet_DisplayShiftOff_CursorIncrement);
}
void Keypad_init()
{
	HAL_Keypad_Init();
}
void EEPROM_init()
{
	HAL_EEPROM_25LC256_Init();
}
void LEDs_init()
{
	HAL_LED_Init(LedGreenEntrance_Port, LedGreenEntrance_PinNumber);
	HAL_LED_Init(LedRedEntrance_Port, LedRedEntrance_PinNumber);
	//HAL_LED_Init(LedGreenExit_Port, LedGreenExit_PinNumber);
	//HAL_LED_Init(LedRedExit_Port, LedRedExit_PinNumber);

}
void USART_init()
{
	USART_Config_t myusartConfig;

	myusartConfig.USART_TxRxMode = USART_TxRxMode_TXandRX;
	myusartConfig.USART_WordLength = USART_WordLength_8BITS;
	myusartConfig.USART_Parity = USART_Parity_NONE;
	myusartConfig.USART_StopBits = USART_StopBits_1BIT;
	myusartConfig.USART_BaudRate = USART_BaudRate_19200bps;
	myusartConfig.USART_FlowControl = USART_FlowControl_NONE;
	myusartConfig.USART_Interrupt_EN = USART_Interrupt_EN_RXNE;

	myusartConfig.USART_ptr_irqCallbackFUN = &myUSART1Handler;
	MCAL_USART_Init(USART1, &myusartConfig);

	myusartConfig.USART_ptr_irqCallbackFUN = &myUSART1Handler;
	MCAL_USART_Init(USART2, &myusartConfig);
}
void Gate_init()
{
	HAL_Servo_Init(Servo_Entrance_Port, Servo_Entrance_PinNumber);
	HAL_IRSensor_Init(IRSensor1_Entrance_Port, IRSensor1_Entrance_PinNumber);
	HAL_Buzzer_Init(Buzzer_Entrance_Port, Buzzer_Entrance_PinNumber);

	HAL_Servo_Init(Servo_Exit_Port, Servo_Exit_PinNumber);
	HAL_IRSensor_Init(IRSensor1_Exit_Port, IRSensor1_Exit_PinNumber);
	HAL_Buzzer_Init(Buzzer_Exit_Port, Buzzer_Exit_PinNumber);

}

int main(void)
{

	clock_init();
	TIM2_init();
	LCD_init();
	Keypad_init();
	EEPROM_init();
	HAL_MemorySIM_Init();
	USART_init();
	LEDs_init();
	Gate_init();

	//char Tx_str = 0x41;
	//HAL_EEPROM_25LC256_Write(0x0000, (uint8_t*) &Tx_str, 1);

	char KeyPressed = 'N';
	while(1)
	{
		HAL_LCD_ClearDisplay();
		HAL_LCD_SendString(" 1.Add   2.Edit ");
		HAL_LCD_SendString(" 3.delete");

		KeyPressed = HAL_Keypad_getPressedKey();


		while( KeyPressed == 'N')
		{
			KeyPressed = HAL_Keypad_getPressedKey();
		}
		switch (KeyPressed)
		{
		case '1':
			APP_Add_RFID();
			break;
		case '2':
			APP_Edit_RFID();
			break;
		case '3':
			APP_Delete_RFID();
			break;
		default:
			break;
		}


	}
}
